# Use a specific version of node:xx-alpine to avoid bugs
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json file to the container's work directory
COPY package.json .

# Install dependencies in the container
RUN npm install

# Copy the rest of your app's source code from your host to your container's work directory
COPY . .

# Define the command to run your app using CMD which defines your runtime
CMD ["npm", "run", "start"]